services:
  html2doc-service:
    image: html2doc:0.0.1
    container_name: html2doc-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - html2doc_storage:/app/tmp/storage
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - default
      - docker_default  # 使用Dify的主网络

volumes:
  html2doc_storage:
    driver: local 

networks:
  default:
  docker_default:  # 引用Dify的主网络
    external: true